"""add pwa_settings

Revision ID: c171d4c48c3a
Revises: 0028
Create Date: 2026-03-21 11:47:29.041803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c171d4c48c3a'
down_revision: Union[str, None] = '0028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('pwa_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('logo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_path')
    op.drop_column('tenants', 'pwa_settings')
    # ### end Alembic commands ###
