"""add pwa_settings

Revision ID: c171d4c48c3a
Revises: 0028
Create Date: 2026-03-21 11:47:29.041803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c171d4c48c3a'
down_revision: Union[str, None] = '0028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixed_report_configs')
    op.drop_index(op.f('idx_print_jobs_tenant_status'), table_name='print_jobs')
    op.drop_table('print_jobs')
    op.drop_index(op.f('idx_print_agents_tenant'), table_name='print_agents')
    op.drop_index(op.f('idx_print_agents_tenant_id'), table_name='print_agents')
    op.drop_table('print_agents')
    op.drop_constraint(op.f('fk_bill_items_tenant_id_tenants'), 'bill_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_tenant_id_tenants'), 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_kot_tickets_tenant_id_tenants'), 'kot_tickets', type_='foreignkey')
    op.drop_index(op.f('idx_menu_item_variants_item_id'), table_name='menu_item_variants')
    op.create_index(op.f('idx_menu_item_variants_tenant_id'), 'menu_item_variants', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_vendor_prices_item'), table_name='menu_item_vendor_prices')
    op.drop_index(op.f('idx_vendor_prices_variant'), table_name='menu_item_vendor_prices')
    op.create_index(op.f('idx_menu_item_vendor_prices_tenant_id'), 'menu_item_vendor_prices', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('fk_menu_items_tenant_id_tenants'), 'menu_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_sections_tenant_id_tenants'), 'sections', type_='foreignkey')
    op.drop_constraint(op.f('fk_table_layouts_tenant_id_tenants'), 'table_layouts', type_='foreignkey')
    op.drop_constraint(op.f('uq_tenant_users_short_code'), 'tenant_users', type_='unique')
    op.add_column('tenants', sa.Column('pwa_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('logo_path', sa.String(), nullable=True))
    op.alter_column('tenants', 'print_template',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text('\'{"phone": "", "kot_width": 32, "gst_number": "", "fssai_number": "", "show_bill_no": true, "show_cashier": true, "receipt_width": 42, "show_token_no": true, "address_line_1": "", "address_line_2": "", "footer_message": "Thanks", "restaurant_name": "", "show_name_field": true}\'::jsonb'))
    op.drop_constraint(op.f('uq_tenants_slug'), 'tenants', type_='unique')
    op.drop_index(op.f('idx_tenants_slug'), table_name='tenants')
    op.create_index(op.f('idx_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_tenants_slug'), table_name='tenants')
    op.create_index(op.f('idx_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_tenants_slug'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'print_template',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text('\'{"phone": "", "kot_width": 32, "gst_number": "", "fssai_number": "", "show_bill_no": true, "show_cashier": true, "receipt_width": 42, "show_token_no": true, "address_line_1": "", "address_line_2": "", "footer_message": "Thanks", "restaurant_name": "", "show_name_field": true}\'::jsonb'))
    op.drop_column('tenants', 'logo_path')
    op.drop_column('tenants', 'pwa_settings')
    op.create_unique_constraint(op.f('uq_tenant_users_short_code'), 'tenant_users', ['tenant_id', 'short_code'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('fk_table_layouts_tenant_id_tenants'), 'table_layouts', 'tenants', ['tenant_id'], ['slug'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_sections_tenant_id_tenants'), 'sections', 'tenants', ['tenant_id'], ['slug'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_menu_items_tenant_id_tenants'), 'menu_items', 'tenants', ['tenant_id'], ['slug'], ondelete='CASCADE')
    op.drop_index(op.f('idx_menu_item_vendor_prices_tenant_id'), table_name='menu_item_vendor_prices')
    op.create_index(op.f('idx_vendor_prices_variant'), 'menu_item_vendor_prices', ['variant_id'], unique=False)
    op.create_index(op.f('idx_vendor_prices_item'), 'menu_item_vendor_prices', ['menu_item_id'], unique=False)
    op.drop_index(op.f('idx_menu_item_variants_tenant_id'), table_name='menu_item_variants')
    op.create_index(op.f('idx_menu_item_variants_item_id'), 'menu_item_variants', ['menu_item_id'], unique=False)
    op.create_foreign_key(op.f('fk_kot_tickets_tenant_id_tenants'), 'kot_tickets', 'tenants', ['tenant_id'], ['slug'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_bills_tenant_id_tenants'), 'bills', 'tenants', ['tenant_id'], ['slug'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_bill_items_tenant_id_tenants'), 'bill_items', 'tenants', ['tenant_id'], ['slug'], ondelete='CASCADE')
    op.create_table('print_agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registration_token_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registration_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('api_key_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'offline'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('printer_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('printer_role', sa.VARCHAR(), server_default=sa.text("'main'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_agents'))
    )
    op.create_index(op.f('idx_print_agents_tenant_id'), 'print_agents', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_print_agents_tenant'), 'print_agents', ['tenant_id'], unique=False)
    op.create_table('print_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bill_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('printer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('target_role', sa.VARCHAR(), server_default=sa.text("'main'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_print_jobs_bill_id_bills'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_jobs'))
    )
    op.create_index(op.f('idx_print_jobs_tenant_status'), 'print_jobs', ['tenant_id', 'status'], unique=False)
    op.create_table('fixed_report_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telegram_schedule', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixed_report_configs')),
    sa.UniqueConstraint('tenant_id', 'report_type', name=op.f('uq_fixed_report_configs_tenant_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
