FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libusb-1.0-0 \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.dev.txt

CMD ["python", "-m", "agent"]
